# Generated by Django 5.2 on 2026-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=12, unique=True)),
                ('jurusan', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
                ('semester', models.IntegerField(max_length=10)),
                ('alamat', models.TextField()),
                ('nomor_hp', models.CharField(max_length=20)),
            ],
        ),
    ]
