# Generated by Django 5.2 on 2026-06-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilmahasiswa',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
