# Generated by Django 5.2 on 2026-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_mahasiswa', '0004_alter_profilmahasiswa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilmahasiswa',
            name='nim',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
