# Generated by Django 5.2 on 2026-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_mahasiswa', '0005_alter_profilmahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilmahasiswa',
            name='nim',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
