# Generated by Django 5.2 on 2026-07-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='period',
            new_name='period_id',
        ),
    ]
