# Generated by Django 5.2 on 2026-07-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_period_question_period_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='period_id',
            new_name='period',
        ),
    ]
