# Generated by Django 5.2 on 2026-07-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_rename_period_id_question_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Akademic', 'Akademic'), ('Non-Akademis', 'Non-Akademis'), ('Reputation', 'Reputation'), ('Access', 'Access'), ('Program Issues', 'Program Issues'), ('Understanding', 'Understanding')], max_length=20, null=True),
        ),
    ]
