# Generated by Django 5.2 on 2026-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Non-Academic', 'Non-Academic'), ('Reputation', 'Reputation'), ('Access', 'Access'), ('Program Issues', 'Program Issues'), ('Understanding', 'Understanding')], max_length=20, null=True),
        ),
    ]
