# Generated by Django 5.2 on 2026-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='period',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Akademik', 'Akademik'), ('Non-Akademik', 'Non-Akademik'), ('Reputasi Universitas', 'Reputasi Universitas'), ('Aksesibilitas/Akses', 'Aksesibilitas/Akses'), ('Isu Program Akademik', 'Isu Program Akademik'), ('Pemahaman Kebutuhan', 'Pemahaman Kebutuhan')], max_length=20, null=True),
        ),
    ]
