# Generated by Django 5.2 on 2026-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_remove_question_order_number_remove_question_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Akademik', 'Akademik'), ('Non-Akademik', 'Non-Akademik'), ('Reputasi Universitas', 'Reputasi Universitas'), ('Aksesibilitas/Akses', 'Aksesibilitas/Akses'), ('Isu Program Akademik', 'Isu Program Akademik'), ('Pemahaman Kebutuhan', 'Pemahaman Kebutuhan')], max_length=30, null=True),
        ),
    ]
