# Generated by Django 5.2 on 2026-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasil_kuesioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilkuesioner',
            name='session_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
