# Generated by Django 5.2 on 2026-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasil_kuesioner', '0002_hasilkuesioner_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuesioner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Home/data gambar wajah/'),
        ),
    ]
