# Generated by Django 5.2 on 2026-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasil_kuesioner', '0003_alter_hasilkuesioner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuesioner',
            name='emotion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hasilkuesioner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='data gambar wajah/'),
        ),
    ]
