# Generated by Django 5.2 on 2026-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_question', '0001_initial'),
        ('question', '0006_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodquestion',
            name='questions',
            field=models.ManyToManyField(related_name='period_questions', to='question.question'),
        ),
    ]
